/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.17.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Yaskawa.Ext.API
{

  /// <summary>
  /// Set of simple control groups combined into a new
  /// control group, optionally designating a master
  /// </summary>
  public partial class CombinedControlGroup : TBase
  {
    private List<global::Yaskawa.Ext.API.SimpleControlGroup> _groups;
    private global::Yaskawa.Ext.API.SimpleControlGroup _master;

    public List<global::Yaskawa.Ext.API.SimpleControlGroup> Groups
    {
      get
      {
        return _groups;
      }
      set
      {
        __isset.groups = true;
        this._groups = value;
      }
    }

    public global::Yaskawa.Ext.API.SimpleControlGroup Master
    {
      get
      {
        return _master;
      }
      set
      {
        __isset.master = true;
        this._master = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool groups;
      public bool master;
    }

    public CombinedControlGroup()
    {
    }

    public CombinedControlGroup DeepCopy()
    {
      var tmp174 = new CombinedControlGroup();
      if((Groups != null) && __isset.groups)
      {
        tmp174.Groups = this.Groups.DeepCopy();
      }
      tmp174.__isset.groups = this.__isset.groups;
      if((Master != null) && __isset.master)
      {
        tmp174.Master = (global::Yaskawa.Ext.API.SimpleControlGroup)this.Master.DeepCopy();
      }
      tmp174.__isset.master = this.__isset.master;
      return tmp174;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.List)
              {
                {
                  var _list175 = await iprot.ReadListBeginAsync(cancellationToken);
                  Groups = new List<global::Yaskawa.Ext.API.SimpleControlGroup>(_list175.Count);
                  for(int _i176 = 0; _i176 < _list175.Count; ++_i176)
                  {
                    global::Yaskawa.Ext.API.SimpleControlGroup _elem177;
                    _elem177 = new global::Yaskawa.Ext.API.SimpleControlGroup();
                    await _elem177.ReadAsync(iprot, cancellationToken);
                    Groups.Add(_elem177);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.Struct)
              {
                Master = new global::Yaskawa.Ext.API.SimpleControlGroup();
                await Master.ReadAsync(iprot, cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp178 = new TStruct("CombinedControlGroup");
        await oprot.WriteStructBeginAsync(tmp178, cancellationToken);
        var tmp179 = new TField();
        if((Groups != null) && __isset.groups)
        {
          tmp179.Name = "groups";
          tmp179.Type = TType.List;
          tmp179.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp179, cancellationToken);
          await oprot.WriteListBeginAsync(new TList(TType.Struct, Groups.Count), cancellationToken);
          foreach (global::Yaskawa.Ext.API.SimpleControlGroup _iter180 in Groups)
          {
            await _iter180.WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Master != null) && __isset.master)
        {
          tmp179.Name = "master";
          tmp179.Type = TType.Struct;
          tmp179.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp179, cancellationToken);
          await Master.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is CombinedControlGroup other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.groups == other.__isset.groups) && ((!__isset.groups) || (TCollections.Equals(Groups, other.Groups))))
        && ((__isset.master == other.__isset.master) && ((!__isset.master) || (global::System.Object.Equals(Master, other.Master))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((Groups != null) && __isset.groups)
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Groups);
        }
        if((Master != null) && __isset.master)
        {
          hashcode = (hashcode * 397) + Master.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp181 = new StringBuilder("CombinedControlGroup(");
      int tmp182 = 0;
      if((Groups != null) && __isset.groups)
      {
        if(0 < tmp182++) { tmp181.Append(", "); }
        tmp181.Append("Groups: ");
        Groups.ToString(tmp181);
      }
      if((Master != null) && __isset.master)
      {
        if(0 < tmp182++) { tmp181.Append(", "); }
        tmp181.Append("Master: ");
        Master.ToString(tmp181);
      }
      tmp181.Append(')');
      return tmp181.ToString();
    }
  }

}
